/**
 * CS2 weapon case list (major retail / drop cases). Steam market hash names match in-game names.
 * Prices are seeded as fallback pence until live market fetch runs.
 */
export const CS2_CASE_CATALOG = [
  { slug: "csgo-weapon-case", name: "CS:GO Weapon Case", steam_market_hash_name: "CS:GO Weapon Case", fallback_price_pence: 45000 },
  { slug: "esports-2013-case", name: "eSports 2013 Case", steam_market_hash_name: "eSports 2013 Case", fallback_price_pence: 120000 },
  { slug: "operation-bravo-case", name: "Operation Bravo Case", steam_market_hash_name: "Operation Bravo Case", fallback_price_pence: 180000 },
  { slug: "csgo-weapon-case-2", name: "CS:GO Weapon Case 2", steam_market_hash_name: "CS:GO Weapon Case 2", fallback_price_pence: 12000 },
  { slug: "csgo-weapon-case-3", name: "CS:GO Weapon Case 3", steam_market_hash_name: "CS:GO Weapon Case 3", fallback_price_pence: 12000 },
  { slug: "winter-offensive-weapon-case", name: "Winter Offensive Weapon Case", steam_market_hash_name: "Winter Offensive Weapon Case", fallback_price_pence: 35000 },
  { slug: "phoenix-weapon-case", name: "Operation Phoenix Weapon Case", steam_market_hash_name: "Operation Phoenix Weapon Case", fallback_price_pence: 18000 },
  { slug: "huntsman-weapon-case", name: "Huntsman Weapon Case", steam_market_hash_name: "Huntsman Weapon Case", fallback_price_pence: 22000 },
  { slug: "breakout-weapon-case", name: "Operation Breakout Weapon Case", steam_market_hash_name: "Operation Breakout Weapon Case", fallback_price_pence: 16000 },
  { slug: "vanguard-weapon-case", name: "Operation Vanguard Weapon Case", steam_market_hash_name: "Operation Vanguard Weapon Case", fallback_price_pence: 15000 },
  { slug: "chroma-case", name: "Chroma Case", steam_market_hash_name: "Chroma Case", fallback_price_pence: 25000 },
  { slug: "chroma-2-case", name: "Chroma 2 Case", steam_market_hash_name: "Chroma 2 Case", fallback_price_pence: 20000 },
  { slug: "bloodhound-weapon-case", name: "Operation Bloodhound Weapon Case", steam_market_hash_name: "Operation Bloodhound Weapon Case", fallback_price_pence: 14000 },
  { slug: "shadow-case", name: "Shadow Case", steam_market_hash_name: "Shadow Case", fallback_price_pence: 13000 },
  { slug: "falchion-case", name: "Falchion Case", steam_market_hash_name: "Falchion Case", fallback_price_pence: 12000 },
  { slug: "chroma-3-case", name: "Chroma 3 Case", steam_market_hash_name: "Chroma 3 Case", fallback_price_pence: 18000 },
  { slug: "revolver-case", name: "Revolver Case", steam_market_hash_name: "Revolver Case", fallback_price_pence: 11000 },
  { slug: "operation-wildfire-case", name: "Operation Wildfire Case", steam_market_hash_name: "Operation Wildfire Case", fallback_price_pence: 16000 },
  { slug: "spectrum-case", name: "Spectrum Case", steam_market_hash_name: "Spectrum Case", fallback_price_pence: 14000 },
  { slug: "gamma-case", name: "Operation Gamma Case", steam_market_hash_name: "Operation Gamma Case", fallback_price_pence: 15000 },
  { slug: "gamma-2-case", name: "Operation Gamma 2 Case", steam_market_hash_name: "Operation Gamma 2 Case", fallback_price_pence: 15000 },
  { slug: "glove-case", name: "Glove Case", steam_market_hash_name: "Glove Case", fallback_price_pence: 45000 },
  { slug: "spectrum-2-case", name: "Spectrum 2 Case", steam_market_hash_name: "Spectrum 2 Case", fallback_price_pence: 13000 },
  { slug: "operation-hydra-case", name: "Operation Hydra Case", steam_market_hash_name: "Operation Hydra Case", fallback_price_pence: 12000 },
  { slug: "clutch-case", name: "Clutch Case", steam_market_hash_name: "Clutch Case", fallback_price_pence: 10000 },
  { slug: "horizon-case", name: "Horizon Case", steam_market_hash_name: "Horizon Case", fallback_price_pence: 9000 },
  { slug: "danger-zone-case", name: "Danger Zone Case", steam_market_hash_name: "Danger Zone Case", fallback_price_pence: 8000 },
  { slug: "prisma-case", name: "Prisma Case", steam_market_hash_name: "Prisma Case", fallback_price_pence: 7000 },
  { slug: "cs20-case", name: "CS20 Case", steam_market_hash_name: "CS20 Case", fallback_price_pence: 9000 },
  { slug: "shattered-web-case", name: "Shattered Web Case", steam_market_hash_name: "Shattered Web Case", fallback_price_pence: 11000 },
  { slug: "prisma-2-case", name: "Prisma 2 Case", steam_market_hash_name: "Prisma 2 Case", fallback_price_pence: 6500 },
  { slug: "fracture-case", name: "Fracture Case", steam_market_hash_name: "Fracture Case", fallback_price_pence: 6000 },
  { slug: "broken-fang-case", name: "Operation Broken Fang Case", steam_market_hash_name: "Operation Broken Fang Case", fallback_price_pence: 10000 },
  { slug: "snakebite-case", name: "Snakebite Case", steam_market_hash_name: "Snakebite Case", fallback_price_pence: 5500 },
  { slug: "operation-riptide-case", name: "Operation Riptide Case", steam_market_hash_name: "Operation Riptide Case", fallback_price_pence: 9000 },
  { slug: "dreams-nightmares-case", name: "Dreams & Nightmares Case", steam_market_hash_name: "Dreams & Nightmares Case", fallback_price_pence: 5000 },
  { slug: "recoil-case", name: "Recoil Case", steam_market_hash_name: "Recoil Case", fallback_price_pence: 4500 },
  { slug: "revolution-case", name: "Revolution Case", steam_market_hash_name: "Revolution Case", fallback_price_pence: 4000 },
  { slug: "kilowatt-case", name: "Kilowatt Case", steam_market_hash_name: "Kilowatt Case", fallback_price_pence: 3500 },
  { slug: "gallery-case", name: "Gallery Case", steam_market_hash_name: "Gallery Case", fallback_price_pence: 3500 },
  { slug: "fever-case", name: "Fever Case", steam_market_hash_name: "Fever Case", fallback_price_pence: 3000 },
  { slug: "armory-case", name: "Armory Case", steam_market_hash_name: "Armory Case", fallback_price_pence: 2500 },
  { slug: "charm-case", name: "Charm Case", steam_market_hash_name: "Charm Case", fallback_price_pence: 2000 },
  { slug: "paris-2023-challengers-sticker-capsule", name: "Paris 2023 Challengers Sticker Capsule", steam_market_hash_name: "Paris 2023 Challengers Sticker Capsule", fallback_price_pence: 1500 },
  { slug: "stockholm-2021-challengers-sticker-capsule", name: "Stockholm 2021 Challengers Sticker Capsule", steam_market_hash_name: "Stockholm 2021 Challengers Sticker Capsule", fallback_price_pence: 1500 },
  { slug: "antwerp-2022-challengers-sticker-capsule", name: "Antwerp 2022 Challengers Sticker Capsule", steam_market_hash_name: "Antwerp 2022 Challengers Sticker Capsule", fallback_price_pence: 1500 },
  { slug: "rio-2022-challengers-sticker-capsule", name: "Rio 2022 Challengers Sticker Capsule", steam_market_hash_name: "Rio 2022 Challengers Sticker Capsule", fallback_price_pence: 1500 },
  { slug: "copenhagen-2024-challengers-sticker-capsule", name: "Copenhagen 2024 Challengers Sticker Capsule", steam_market_hash_name: "Copenhagen 2024 Challengers Sticker Capsule", fallback_price_pence: 1500 },
  { slug: "paris-2023-legends-sticker-capsule", name: "Paris 2023 Legends Sticker Capsule", steam_market_hash_name: "Paris 2023 Legends Sticker Capsule", fallback_price_pence: 1500 },
  { slug: "paris-2023-contenders-sticker-capsule", name: "Paris 2023 Contenders Sticker Capsule", steam_market_hash_name: "Paris 2023 Contenders Sticker Capsule", fallback_price_pence: 1500 }
];
