interface D1Result<T> { results: T[]; }
interface D1Statement {
  bind(...values: unknown[]): D1Statement;
  first<T = Record<string, unknown>>(): Promise<T | null>;
  all<T = Record<string, unknown>>(): Promise<D1Result<T>>;
  run(): Promise<unknown>;
}
interface D1Database { prepare(query: string): D1Statement; batch(statements: D1Statement[]): Promise<unknown[]>; }

export interface ChatProgressionEnv {
  DB: D1Database;
  APP_ENV: 'development' | 'pbe' | 'production';
}

type User = { id:string; username:string; displayName:string; isVerified:boolean; isOwner:boolean; isAdmin:boolean };
type Room = { id:string; room_type:'global'|'group'|'direct'; group_id:string|null; title:string; created_by:string|null; created_at:number; updated_at:number };
type Achievement = { id:string; name:string; description:string; image_url:string; xp_reward:number; category:string; criteria_type:string; criteria_value:number; sort_order:number };

const COOKIE='grev_session';
const encoder=new TextEncoder();
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const ROOM_RE=/^(chat-global|[0-9a-f-]{36})$/i;
const GIF_DATA=/^data:image\/gif;base64,([a-z0-9+/]+={0,2})$/i;
const MAX_GIF_BYTES=1_400_000;

function b64(bytes:Uint8Array):string{return btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');}
async function sha256(value:string):Promise<string>{return b64(new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(value))));}
function cookies(request:Request):Record<string,string>{return Object.fromEntries((request.headers.get('Cookie')??'').split(';').map(v=>v.trim()).filter(Boolean).map(v=>{const i=v.indexOf('=');return i<0?['','']:[v.slice(0,i),decodeURIComponent(v.slice(i+1))];}).filter(([k])=>k));}
async function userFromRequest(request:Request,env:ChatProgressionEnv):Promise<User|null>{const token=cookies(request)[COOKIE];if(!token)return null;const row=await env.DB.prepare(`SELECT u.id,u.username,u.display_name,u.is_verified,u.is_owner,CASE WHEN u.is_owner=1 OR EXISTS(SELECT 1 FROM user_roles ur WHERE ur.user_id=u.id AND ur.role_id='role-admin') THEN 1 ELSE 0 END is_admin FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.revoked_at IS NULL AND s.expires_at>? AND u.status='active'`).bind(await sha256(token),Math.floor(Date.now()/1000)).first<{id:string;username:string;display_name:string;is_verified:number;is_owner:number;is_admin:number}>();return row?{id:row.id,username:row.username,displayName:row.display_name,isVerified:Boolean(row.is_verified),isOwner:Boolean(row.is_owner),isAdmin:Boolean(row.is_admin)}:null;}
function json(value:unknown,status=200):Response{return new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin','X-Frame-Options':'DENY','Permissions-Policy':'camera=(), microphone=(), geolocation=()'}});}
function sameOrigin(request:Request):boolean{const origin=request.headers.get('Origin');return !origin||origin===new URL(request.url).origin;}
async function readBody(request:Request):Promise<Record<string,unknown>>{if(!(request.headers.get('Content-Type')??'').includes('application/json'))throw new Error('JSON_REQUIRED');const value:unknown=await request.json();if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('INVALID_BODY');return value as Record<string,unknown>;}
function now():number{return Math.floor(Date.now()/1000);}
function dataBytes(value:string):number{const encoded=value.slice(value.indexOf(',')+1);const padding=encoded.endsWith('==')?2:encoded.endsWith('=')?1:0;return Math.floor(encoded.length*3/4)-padding;}
function validGif(value:string):boolean{if(/^https:\/\//i.test(value)){try{return new URL(value).protocol==='https:';}catch{return false;}}const match=value.match(GIF_DATA);if(!match||dataBytes(value)>MAX_GIF_BYTES)return false;try{return atob(match[1]!.slice(0,12)).startsWith('GIF8');}catch{return false;}}
function levelInfo(totalXp:number){const level=Math.floor(totalXp/500)+1;const current=totalXp%500;return{totalXp,level,currentLevelXp:current,nextLevelXp:500,progressPercent:Math.round(current/500*100)};}

async function ensureProgress(env:ChatProgressionEnv,userId:string){await env.DB.prepare(`INSERT OR IGNORE INTO user_progression(user_id,total_xp,level,updated_at) VALUES(?,0,1,?)`).bind(userId,now()).run();}
async function grantXp(env:ChatProgressionEnv,userId:string,amount:number,sourceType:string,sourceId:string|null,eventKey:string,description:string):Promise<boolean>{await ensureProgress(env,userId);const exists=await env.DB.prepare(`SELECT 1 ok FROM xp_ledger WHERE event_key=?`).bind(eventKey).first();if(exists)return false;const created=now();await env.DB.batch([env.DB.prepare(`INSERT INTO xp_ledger(id,user_id,xp_amount,source_type,source_id,event_key,description,created_at) VALUES(?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),userId,amount,sourceType,sourceId,eventKey,description,created),env.DB.prepare(`UPDATE user_progression SET total_xp=total_xp+?,level=CAST((total_xp+?)/500 AS INTEGER)+1,updated_at=? WHERE user_id=?`).bind(amount,amount,created,userId)]);return true;}
async function awardAchievement(env:ChatProgressionEnv,userId:string,achievement:Achievement,progress:number):Promise<boolean>{const exists=await env.DB.prepare(`SELECT 1 ok FROM user_achievements WHERE user_id=? AND achievement_id=?`).bind(userId,achievement.id).first();if(exists)return false;const awarded=now();await env.DB.prepare(`INSERT INTO user_achievements(user_id,achievement_id,awarded_at,progress_value) VALUES(?,?,?,?)`).bind(userId,achievement.id,awarded,progress).run();await grantXp(env,userId,achievement.xp_reward,'achievement',achievement.id,`achievement:${userId}:${achievement.id}`,achievement.name);await env.DB.prepare(`INSERT INTO notifications(id,recipient_user_id,notification_type,title,body,target_url,metadata_json,created_at) VALUES(?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),userId,'achievement.unlocked',`Achievement unlocked: ${achievement.name}`,`${achievement.description} +${achievement.xp_reward} XP`,'/profile#achievements',JSON.stringify({achievementId:achievement.id}),awarded).run();return true;}
async function criteriaValue(env:ChatProgressionEnv,userId:string,type:string):Promise<number>{let query='';switch(type){case'profile_saved':query=`SELECT COUNT(*) count FROM user_profiles WHERE user_id=?`;break;case'profile_updates':query=`SELECT COUNT(*) count FROM audit_events WHERE actor_user_id=? AND event_type LIKE 'profile.%updated%'`;break;case'dashboard_versions':query=`SELECT COUNT(*) count FROM dashboard_layout_versions WHERE user_id=?`;break;case'tasks_created':query=`SELECT COUNT(*) count FROM content_items WHERE owner_user_id=? AND item_type='task'`;break;case'tasks_completed':query=`SELECT COUNT(*) count FROM content_items WHERE owner_user_id=? AND item_type='task' AND completed_at IS NOT NULL`;break;case'chat_messages':query=`SELECT COUNT(*) count FROM chat_messages WHERE sender_user_id=? AND deleted_at IS NULL`;break;case'global_messages':query=`SELECT COUNT(*) count FROM chat_messages m JOIN chat_rooms r ON r.id=m.room_id WHERE m.sender_user_id=? AND m.deleted_at IS NULL AND r.room_type='global'`;break;case'group_messages':query=`SELECT COUNT(*) count FROM chat_messages m JOIN chat_rooms r ON r.id=m.room_id WHERE m.sender_user_id=? AND m.deleted_at IS NULL AND r.room_type='group'`;break;case'achievements_earned':query=`SELECT COUNT(*) count FROM user_achievements WHERE user_id=?`;break;default:return 0;}const row=await env.DB.prepare(query).bind(userId).first<{count:number}>();return Number(row?.count??0);}
async function syncAchievements(env:ChatProgressionEnv,userId:string){await ensureProgress(env,userId);const definitions=await env.DB.prepare(`SELECT id,name,description,image_url,xp_reward,category,criteria_type,criteria_value,sort_order FROM achievement_definitions WHERE is_active=1 ORDER BY sort_order`).all<Achievement>();let changed=true;let passes=0;while(changed&&passes<2){changed=false;passes+=1;for(const achievement of definitions.results){const value=await criteriaValue(env,userId,achievement.criteria_type);if(value>=achievement.criteria_value&&await awardAchievement(env,userId,achievement,value))changed=true;}}}

async function syncSiteXp(env:ChatProgressionEnv,userId:string){
  await ensureProgress(env,userId);
  await grantXp(env,userId,50,'account',userId,`account:${userId}`,'Joined Grev.dad');
  const audits=await env.DB.prepare(`SELECT id,event_type FROM audit_events WHERE actor_user_id=? AND (event_type LIKE 'profile.%' OR event_type LIKE 'dashboard.%') ORDER BY created_at LIMIT 1000`).bind(userId).all<{id:string;event_type:string}>();
  for(const event of audits.results){const amount=event.event_type.startsWith('profile.')?15:10;await grantXp(env,userId,amount,'audit',event.id,`audit:${userId}:${event.id}`,event.event_type.replaceAll('.',' '));}
  const versions=await env.DB.prepare(`SELECT id FROM dashboard_layout_versions WHERE user_id=? ORDER BY created_at LIMIT 500`).bind(userId).all<{id:string}>();
  for(const version of versions.results)await grantXp(env,userId,15,'dashboard_version',version.id,`dashboard-version:${userId}:${version.id}`,'Saved a dashboard layout version');
  const items=await env.DB.prepare(`SELECT id,item_type,completed_at FROM content_items WHERE owner_user_id=? ORDER BY created_at LIMIT 1000`).bind(userId).all<{id:string;item_type:string;completed_at:number|null}>();
  for(const item of items.results){await grantXp(env,userId,10,'content_item',item.id,`content:${userId}:${item.id}`,`Created ${item.item_type}`);if(item.completed_at&&['task','reminder'].includes(item.item_type))await grantXp(env,userId,25,'content_complete',item.id,`content-complete:${userId}:${item.id}`,`Completed ${item.item_type}`);}
  const guestbook=await env.DB.prepare(`SELECT id FROM profile_guestbook_entries WHERE author_user_id=? AND deleted_at IS NULL ORDER BY created_at LIMIT 500`).bind(userId).all<{id:string}>();
  for(const entry of guestbook.results)await grantXp(env,userId,8,'guestbook',entry.id,`guestbook:${userId}:${entry.id}`,'Posted a guestbook message');
  const reactions=await env.DB.prepare(`SELECT profile_user_id,reaction FROM profile_reactions WHERE author_user_id=?`).bind(userId).all<{profile_user_id:string;reaction:string}>();
  for(const reaction of reactions.results)await grantXp(env,userId,3,'profile_reaction',reaction.profile_user_id,`reaction:${userId}:${reaction.profile_user_id}`,'Reacted to a profile');
  const subscriptions=await env.DB.prepare(`SELECT profile_user_id FROM profile_subscriptions WHERE subscriber_user_id=?`).bind(userId).all<{profile_user_id:string}>();
  for(const subscription of subscriptions.results)await grantXp(env,userId,3,'profile_subscription',subscription.profile_user_id,`subscription:${userId}:${subscription.profile_user_id}`,'Subscribed to a profile');
  await syncAchievements(env,userId);
}


async function ensureGroupRooms(env:ChatProgressionEnv,user:User){const groups=await env.DB.prepare(`SELECT g.id,g.name FROM groups g JOIN group_memberships gm ON gm.group_id=g.id WHERE gm.user_id=?`).bind(user.id).all<{id:string;name:string}>();for(const group of groups.results){let room=await env.DB.prepare(`SELECT id FROM chat_rooms WHERE room_type='group' AND group_id=?`).bind(group.id).first<{id:string}>();if(!room){const id=crypto.randomUUID();await env.DB.prepare(`INSERT INTO chat_rooms(id,room_type,group_id,title,created_by,created_at,updated_at) VALUES(?,'group',?,?,?,?,?)`).bind(id,group.id,`${group.name} chat`,user.id,now(),now()).run();room={id};}await env.DB.prepare(`INSERT OR IGNORE INTO chat_members(room_id,user_id,joined_at) VALUES(?,?,?)`).bind(room.id,user.id,now()).run();}}
async function roomAccess(env:ChatProgressionEnv,user:User,roomId:string):Promise<Room|null>{const room=await env.DB.prepare(`SELECT id,room_type,group_id,title,created_by,created_at,updated_at FROM chat_rooms WHERE id=?`).bind(roomId).first<Room>();if(!room)return null;if(room.room_type==='global')return room;if(room.room_type==='group'){if(user.isAdmin||await env.DB.prepare(`SELECT 1 ok FROM group_memberships WHERE group_id=? AND user_id=?`).bind(room.group_id,user.id).first())return room;return null;}return await env.DB.prepare(`SELECT 1 ok FROM chat_members WHERE room_id=? AND user_id=?`).bind(roomId,user.id).first()?room:null;}
async function roomParticipant(env:ChatProgressionEnv,roomId:string,userId:string){return env.DB.prepare(`SELECT u.id,u.username,u.display_name,u.is_verified,u.is_owner,CASE WHEN u.is_owner=1 OR EXISTS(SELECT 1 FROM user_roles ur WHERE ur.user_id=u.id AND ur.role_id='role-admin') THEN 1 ELSE 0 END is_admin,p.avatar_media,COALESCE(up.total_xp,0) total_xp,COALESCE(up.level,1) level FROM chat_members cm JOIN users u ON u.id=cm.user_id LEFT JOIN user_profiles p ON p.user_id=u.id LEFT JOIN user_progression up ON up.user_id=u.id WHERE cm.room_id=? AND u.id<>? LIMIT 1`).bind(roomId,userId).first<{id:string;username:string;display_name:string;is_verified:number;is_owner:number;is_admin:number;avatar_media:string|null;total_xp:number;level:number}>();}
function userCard(row:{id:string;username:string;display_name:string;is_verified:number;is_owner:number;is_admin:number;avatar_media:string|null;total_xp:number;level:number}){return{id:row.id,username:row.username,displayName:row.display_name,isVerified:Boolean(row.is_verified),role:row.is_owner?'Owner':row.is_admin?'Administrator':'Member',avatarMedia:row.avatar_media,...levelInfo(Number(row.total_xp??0))};}

async function listRooms(env:ChatProgressionEnv,user:User):Promise<Response>{await ensureGroupRooms(env,user);await env.DB.prepare(`INSERT OR IGNORE INTO chat_members(room_id,user_id,joined_at) VALUES('chat-global',?,?)`).bind(user.id,now()).run();const rows=await env.DB.prepare(`
 SELECT r.id,r.room_type,r.group_id,r.title,r.updated_at,
   (SELECT body FROM chat_messages m WHERE m.room_id=r.id AND m.deleted_at IS NULL ORDER BY m.created_at DESC LIMIT 1) last_body,
   (SELECT message_type FROM chat_messages m WHERE m.room_id=r.id AND m.deleted_at IS NULL ORDER BY m.created_at DESC LIMIT 1) last_type,
   (SELECT created_at FROM chat_messages m WHERE m.room_id=r.id AND m.deleted_at IS NULL ORDER BY m.created_at DESC LIMIT 1) last_created,
   (SELECT COUNT(*) FROM chat_messages m WHERE m.room_id=r.id AND m.deleted_at IS NULL AND m.sender_user_id<>? AND m.created_at>COALESCE(cm.last_read_at,0)) unread
 FROM chat_rooms r
 LEFT JOIN chat_members cm ON cm.room_id=r.id AND cm.user_id=?
 WHERE r.room_type='global'
 OR (r.room_type='group' AND EXISTS(SELECT 1 FROM group_memberships gm WHERE gm.group_id=r.group_id AND gm.user_id=?))
 OR (r.room_type='direct' AND cm.user_id IS NOT NULL)
 ORDER BY CASE WHEN last_created IS NULL THEN 1 ELSE 0 END,last_created DESC,r.title
 `).bind(user.id,user.id,user.id).all<{id:string;room_type:'global'|'group'|'direct';group_id:string|null;title:string;updated_at:number;last_body:string|null;last_type:string|null;last_created:number|null;unread:number}>();const rooms=[];for(const row of rows.results){const other=row.room_type==='direct'?await roomParticipant(env,row.id,user.id):null;rooms.push({id:row.id,type:row.room_type,groupId:row.group_id,title:other?other.display_name:row.title,lastMessage:row.last_type==='gif'?'GIF':row.last_body,lastCreatedAt:row.last_created,unread:Number(row.unread),participant:other?userCard(other):null});}return json({ok:true,rooms});}

async function createDirect(request:Request,env:ChatProgressionEnv,user:User):Promise<Response>{const input=await readBody(request);const targetId=String(input.userId??'');if(!UUID_RE.test(targetId)||targetId===user.id)return json({ok:false,message:'Choose another member.'},400);const target=await env.DB.prepare(`SELECT id,display_name FROM users WHERE id=? AND status='active'`).bind(targetId).first<{id:string;display_name:string}>();if(!target)return json({ok:false,message:'Member not found.'},404);let room=await env.DB.prepare(`SELECT r.id FROM chat_rooms r JOIN chat_members a ON a.room_id=r.id AND a.user_id=? JOIN chat_members b ON b.room_id=r.id AND b.user_id=? WHERE r.room_type='direct' LIMIT 1`).bind(user.id,targetId).first<{id:string}>();if(!room){const id=crypto.randomUUID(),created=now();await env.DB.batch([env.DB.prepare(`INSERT INTO chat_rooms(id,room_type,title,created_by,created_at,updated_at) VALUES(?,'direct','',?,?,?)`).bind(id,user.id,created,created),env.DB.prepare(`INSERT INTO chat_members(room_id,user_id,member_role,joined_at,last_read_at) VALUES(?,?,'owner',?,?)`).bind(id,user.id,created,created),env.DB.prepare(`INSERT INTO chat_members(room_id,user_id,joined_at) VALUES(?,?,?)`).bind(id,targetId,created)]);room={id};}return json({ok:true,roomId:room.id});}

async function messages(request:Request,env:ChatProgressionEnv,user:User,roomId:string):Promise<Response>{const room=await roomAccess(env,user,roomId);if(!room)return json({ok:false,message:'Chat not found.'},404);const url=new URL(request.url);const after=Math.max(0,Number(url.searchParams.get('after')??0));const rows=await env.DB.prepare(`SELECT m.id,m.message_type,m.body,m.media_url,m.reply_to_id,m.created_at,m.edited_at,m.sender_user_id,u.username,u.display_name,u.is_verified,u.is_owner,CASE WHEN u.is_owner=1 OR EXISTS(SELECT 1 FROM user_roles ur WHERE ur.user_id=u.id AND ur.role_id='role-admin') THEN 1 ELSE 0 END is_admin,p.avatar_media,COALESCE(up.total_xp,0) total_xp,COALESCE(up.level,1) level FROM chat_messages m JOIN users u ON u.id=m.sender_user_id LEFT JOIN user_profiles p ON p.user_id=u.id LEFT JOIN user_progression up ON up.user_id=u.id WHERE m.room_id=? AND m.deleted_at IS NULL AND m.created_at>=? ORDER BY m.created_at ASC LIMIT 150`).bind(roomId,after).all<{id:string;message_type:string;body:string;media_url:string|null;reply_to_id:string|null;created_at:number;edited_at:number|null;sender_user_id:string;username:string;display_name:string;is_verified:number;is_owner:number;is_admin:number;avatar_media:string|null;total_xp:number;level:number}>();await env.DB.prepare(`INSERT INTO chat_members(room_id,user_id,joined_at,last_read_at) VALUES(?,?,?,?) ON CONFLICT(room_id,user_id) DO UPDATE SET last_read_at=excluded.last_read_at`).bind(roomId,user.id,now(),now()).run();return json({ok:true,room:{id:room.id,type:room.room_type,title:room.title,groupId:room.group_id,participant:room.room_type==='direct'?await roomParticipant(env,room.id,user.id).then(row=>row?userCard(row):null):null},messages:rows.results.map(row=>({id:row.id,type:row.message_type,body:row.body,mediaUrl:row.media_url,replyToId:row.reply_to_id,createdAt:row.created_at,editedAt:row.edited_at,isOwn:row.sender_user_id===user.id,sender:userCard(row)}))});}

async function postMessage(request:Request,env:ChatProgressionEnv,user:User,roomId:string):Promise<Response>{const room=await roomAccess(env,user,roomId);if(!room)return json({ok:false,message:'Chat not found.'},404);const input=await readBody(request);const messageType=String(input.type??'text');const text=String(input.body??'').trim();const mediaUrl=input.mediaUrl?String(input.mediaUrl):null;const replyToId=input.replyToId?String(input.replyToId):null;if(!['text','gif'].includes(messageType))return json({ok:false,message:'Unsupported message type.'},400);if(messageType==='text'&&(!text||text.length>2000))return json({ok:false,message:'Messages must be between 1 and 2,000 characters.'},400);if(messageType==='gif'&&(!mediaUrl||!validGif(mediaUrl)))return json({ok:false,message:'Choose a valid HTTPS GIF or GIF upload.'},400);if(replyToId&&!UUID_RE.test(replyToId))return json({ok:false,message:'Invalid reply.'},400);if(replyToId&&!await env.DB.prepare(`SELECT 1 ok FROM chat_messages WHERE id=? AND room_id=? AND deleted_at IS NULL`).bind(replyToId,roomId).first())return json({ok:false,message:'The replied-to message is not in this chat.'},400);const id=crypto.randomUUID(),created=now();await env.DB.batch([env.DB.prepare(`INSERT INTO chat_messages(id,room_id,sender_user_id,message_type,body,media_url,reply_to_id,created_at) VALUES(?,?,?,?,?,?,?,?)`).bind(id,roomId,user.id,messageType,text,mediaUrl,replyToId,created),env.DB.prepare(`UPDATE chat_rooms SET updated_at=? WHERE id=?`).bind(created,roomId),env.DB.prepare(`INSERT INTO chat_members(room_id,user_id,joined_at,last_read_at) VALUES(?,?,?,?) ON CONFLICT(room_id,user_id) DO UPDATE SET last_read_at=excluded.last_read_at`).bind(roomId,user.id,created,created)]);await grantXp(env,user.id,5,'chat_message',id,`chat-message:${id}`,'Sent a chat message');await syncAchievements(env,user.id);if(room.room_type==='direct'){const members=await env.DB.prepare(`SELECT user_id FROM chat_members WHERE room_id=? AND user_id<>?`).bind(roomId,user.id).all<{user_id:string}>();for(const member of members.results)await env.DB.prepare(`INSERT INTO notifications(id,recipient_user_id,actor_user_id,notification_type,title,body,target_url,metadata_json,created_at) VALUES(?,?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),member.user_id,user.id,'chat.message',`New message from ${user.displayName}`,messageType==='gif'?'Sent a GIF':text.slice(0,180),`/dashboard#chat-${roomId}`,JSON.stringify({roomId,messageId:id}),created).run();}return messages(new Request(new URL(`/api/chat/rooms/${roomId}/messages?after=${created-1}`,request.url),request),env,user,roomId);}

async function progression(env:ChatProgressionEnv,viewer:User,userId:string):Promise<Response>{if(!UUID_RE.test(userId))return json({ok:false,message:'Profile not found.'},404);await syncSiteXp(env,userId);const [profile,earned,catalog,ledger]=await Promise.all([env.DB.prepare(`SELECT COALESCE(up.total_xp,0) total_xp,COALESCE(up.level,1) level,u.username,u.display_name,u.is_verified,u.is_owner,CASE WHEN u.is_owner=1 OR EXISTS(SELECT 1 FROM user_roles ur WHERE ur.user_id=u.id AND ur.role_id='role-admin') THEN 1 ELSE 0 END is_admin,p.avatar_media FROM users u LEFT JOIN user_progression up ON up.user_id=u.id LEFT JOIN user_profiles p ON p.user_id=u.id WHERE u.id=? AND u.status='active'`).bind(userId).first<{total_xp:number;level:number;username:string;display_name:string;is_verified:number;is_owner:number;is_admin:number;avatar_media:string|null}>(),env.DB.prepare(`SELECT a.id,a.name,a.description,a.image_url,a.xp_reward,a.category,ua.awarded_at,ua.progress_value FROM user_achievements ua JOIN achievement_definitions a ON a.id=ua.achievement_id WHERE ua.user_id=? ORDER BY ua.awarded_at DESC`).bind(userId).all(),env.DB.prepare(`SELECT id,name,description,image_url,xp_reward,category,criteria_type,criteria_value,sort_order FROM achievement_definitions WHERE is_active=1 ORDER BY sort_order`).all<Achievement>(),env.DB.prepare(`SELECT xp_amount,source_type,description,created_at FROM xp_ledger WHERE user_id=? ORDER BY created_at DESC LIMIT 20`).bind(userId).all()]);if(!profile)return json({ok:false,message:'Profile not found.'},404);const earnedIds=new Set((earned.results as {id:string}[]).map(item=>item.id));const criteria:Record<string,number>={};if(viewer.id===userId){for(const achievement of catalog.results)criteria[achievement.criteria_type]??=await criteriaValue(env,userId,achievement.criteria_type);}return json({ok:true,profile:{id:userId,username:profile.username,displayName:profile.display_name,isVerified:Boolean(profile.is_verified),role:profile.is_owner?'Owner':profile.is_admin?'Administrator':'Member',avatarMedia:profile.avatar_media,...levelInfo(Number(profile.total_xp??0))},achievements:catalog.results.map(a=>({...a,earned:earnedIds.has(a.id),progress:viewer.id===userId?Math.min(criteria[a.criteria_type]??0,a.criteria_value):null})),earned:earned.results,recentXp:viewer.id===userId?ledger.results:[]});}

export async function handleChatProgressionRequest(request:Request,env:ChatProgressionEnv):Promise<Response|null>{const path=new URL(request.url).pathname;if(!path.startsWith('/api/chat')&&!path.startsWith('/api/progression')&&!path.startsWith('/api/achievements'))return null;const user=await userFromRequest(request,env);if(!user)return json({ok:false,message:'Authentication required.'},401);if(request.method!=='GET'&&!sameOrigin(request))return json({ok:false,message:'Origin rejected.'},403);
 if(path==='/api/chat/rooms'&&request.method==='GET')return listRooms(env,user);
 if(path==='/api/chat/direct'&&request.method==='POST')return createDirect(request,env,user);
 const roomMessages=path.match(/^\/api\/chat\/rooms\/(chat-global|[0-9a-f-]{36})\/messages$/i);if(roomMessages&&request.method==='GET')return messages(request,env,user,roomMessages[1]!);if(roomMessages&&request.method==='POST')return postMessage(request,env,user,roomMessages[1]!);
 if(path==='/api/progression/sync'&&request.method==='POST')return progression(env,user,user.id);
 const progress=path.match(/^\/api\/progression\/([0-9a-f-]{36})$/i);if(progress&&request.method==='GET')return progression(env,user,progress[1]!);
 if(path==='/api/achievements'&&request.method==='GET')return progression(env,user,user.id);
 return json({ok:false,message:'Not found.'},404);
}
