export interface D1Result<T>{results:T[]}
export interface D1Statement{bind(...values:unknown[]):D1Statement;first<T=Record<string,unknown>>():Promise<T|null>;all<T=Record<string,unknown>>():Promise<D1Result<T>>;run():Promise<unknown>}
export interface D1Database{prepare(query:string):D1Statement;batch(statements:D1Statement[]):Promise<unknown[]>}
export interface PlatformCompletionEnv{DB:D1Database;APP_ENV:'development'|'pbe'|'production'}
export type Viewer={id:string;username:string;displayName:string;isVerified:boolean;isAdmin:boolean};
export const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export const REACTIONS=new Set(['wave','heart','fire','clap']);
const COOKIE='grev_session';
const encoder=new TextEncoder();
function b64(bytes:Uint8Array){return btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
async function sha256(value:string){return b64(new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(value))))}
function cookies(request:Request):Record<string,string>{return Object.fromEntries((request.headers.get('Cookie')??'').split(';').map(value=>value.trim()).filter(Boolean).map(value=>{const index=value.indexOf('=');return index<0?['','']:[value.slice(0,index),decodeURIComponent(value.slice(index+1))]}).filter(([key])=>Boolean(key)))}
export async function viewerFromRequest(request:Request,env:PlatformCompletionEnv):Promise<Viewer|null>{const token=cookies(request)[COOKIE];if(!token)return null;const row=await env.DB.prepare(`SELECT u.id,u.username,u.display_name,u.is_verified,CASE WHEN u.is_owner=1 OR EXISTS(SELECT 1 FROM user_roles ur WHERE ur.user_id=u.id AND ur.role_id='role-admin') THEN 1 ELSE 0 END is_admin FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.revoked_at IS NULL AND s.expires_at>? AND u.status='active'`).bind(await sha256(token),Math.floor(Date.now()/1000)).first<{id:string;username:string;display_name:string;is_verified:number;is_admin:number}>();return row?{id:row.id,username:row.username,displayName:row.display_name,isVerified:Boolean(row.is_verified),isAdmin:Boolean(row.is_admin)}:null}
export function json(value:unknown,status=200){return new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin','X-Frame-Options':'DENY','Permissions-Policy':'camera=(), microphone=(), geolocation=()'}})}
export function sameOrigin(request:Request){const origin=request.headers.get('Origin');return !origin||origin===new URL(request.url).origin}
export async function readBody(request:Request):Promise<Record<string,unknown>>{if(!(request.headers.get('Content-Type')??'').includes('application/json'))throw new Error('JSON_REQUIRED');const value:unknown=await request.json();if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('INVALID_BODY');return value as Record<string,unknown>}
export function now(){return Math.floor(Date.now()/1000)}
export async function audit(env:PlatformCompletionEnv,actor:string,type:string,targetType:string,targetId:string|null,metadata:unknown={}){await env.DB.prepare(`INSERT INTO audit_events(id,actor_user_id,event_type,target_type,target_id,metadata_json,created_at) VALUES(?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),actor,type,targetType,targetId,JSON.stringify(metadata),now()).run()}
export async function notify(env:PlatformCompletionEnv,recipient:string,actor:string|null,type:string,title:string,text:string,targetUrl:string|null,metadata:unknown={}){if(recipient===actor)return;await env.DB.prepare(`INSERT INTO notifications(id,recipient_user_id,actor_user_id,notification_type,title,body,target_url,metadata_json,created_at) VALUES(?,?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),recipient,actor,type,title.slice(0,120),text.slice(0,500),targetUrl,JSON.stringify(metadata),now()).run()}
export async function changeToken(env:PlatformCompletionEnv){const row=await env.DB.prepare(`SELECT (SELECT COALESCE(MAX(updated_at),0) FROM content_items) content_updated,(SELECT COUNT(*) FROM content_items) content_count,(SELECT COALESCE(MAX(created_at),0) FROM notifications) notification_created,(SELECT COALESCE(MAX(COALESCE(read_at,created_at)),0) FROM notifications) notification_state,(SELECT COUNT(*) FROM notifications) notification_count,(SELECT COALESCE(MAX(updated_at),0) FROM user_presence) presence_updated,(SELECT COALESCE(MAX(updated_at),0) FROM dashboard_pages) pages_updated,(SELECT COALESCE(MAX(created_at),0) FROM profile_guestbook_entries) guestbook_created,(SELECT COALESCE(MAX(updated_at),0) FROM profile_guestbook_entries) guestbook_updated,(SELECT COALESCE(MAX(deleted_at),0) FROM profile_guestbook_entries) guestbook_deleted,(SELECT COUNT(*) FROM profile_guestbook_entries WHERE deleted_at IS NULL) guestbook_count,(SELECT COALESCE(MAX(created_at),0) FROM profile_reactions) reactions_updated,(SELECT COUNT(*) FROM profile_reactions) reaction_count,(SELECT COALESCE(MAX(created_at),0) FROM profile_guestbook_reports) reports_updated,(SELECT COUNT(*) FROM profile_guestbook_reports) reports_count,(SELECT COALESCE(MAX(created_at),0) FROM profile_blocks) blocks_updated,(SELECT COUNT(*) FROM profile_blocks) blocks_count,(SELECT COALESCE(MAX(created_at),0) FROM profile_subscriptions) subscriptions_updated,(SELECT COUNT(*) FROM profile_subscriptions) subscriptions_count,(SELECT COALESCE(MAX(visited_at),0) FROM profile_visits) visits_updated,(SELECT COALESCE(MAX(created_at),0) FROM chat_messages) chat_updated,(SELECT COUNT(*) FROM chat_messages WHERE deleted_at IS NULL) chat_count`).first<Record<string,unknown>>();return b64(encoder.encode(JSON.stringify(row??{})))}
export function eventStream(env:PlatformCompletionEnv,since:string){let cancelled=false;const stream=new ReadableStream<Uint8Array>({start(controller){void(async()=>{let last=since;try{for(let cycle=0;cycle<22&&!cancelled;cycle+=1){const token=await changeToken(env);if(token!==last){last=token;controller.enqueue(encoder.encode(`event: change\ndata: ${JSON.stringify({token})}\n\n`))}else if(cycle%5===0)controller.enqueue(encoder.encode(`event: ping\ndata: ${JSON.stringify({at:Date.now()})}\n\n`));await new Promise(resolve=>setTimeout(resolve,2500))}if(!cancelled)controller.close()}catch(error){if(!cancelled)controller.error(error)}})()},cancel(){cancelled=true}});return new Response(stream,{headers:{'Content-Type':'text/event-stream; charset=utf-8','Cache-Control':'no-cache, no-store','Connection':'keep-alive','X-Accel-Buffering':'no'}})}
