interface D1Result<T>{results:T[]}
interface D1Statement{bind(...values:unknown[]):D1Statement;first<T=Record<string,unknown>>():Promise<T|null>;all<T=Record<string,unknown>>():Promise<D1Result<T>>;run():Promise<unknown>}
interface D1Database{prepare(query:string):D1Statement}
export interface FeedbackCentreEnv{DB:D1Database;APP_ENV:'development'|'pbe'|'production'}
type Viewer={id:string;username:string;displayName:string;isAdmin:boolean;isOwner:boolean}
const COOKIE='grev_session';
const encoder=new TextEncoder();
const CATEGORIES=new Set(['broken','visual','confusing','suggestion','general']);
const STATUSES=new Set(['new','investigating','fixed','cannot_reproduce','planned','closed']);
const SEVERITIES=new Set(['low','medium','high','critical']);
function b64(bytes:Uint8Array){return btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
async function sha256(value:string){return b64(new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(value))))}
function cookies(request:Request):Record<string,string>{return Object.fromEntries((request.headers.get('Cookie')??'').split(';').map(value=>value.trim()).filter(Boolean).map(value=>{const index=value.indexOf('=');return index<0?['','']:[value.slice(0,index),decodeURIComponent(value.slice(index+1))]}).filter(([key])=>Boolean(key)))}
async function viewerFromRequest(request:Request,env:FeedbackCentreEnv):Promise<Viewer|null>{const token=cookies(request)[COOKIE];if(!token)return null;const row=await env.DB.prepare(`SELECT u.id,u.username,u.display_name,u.is_owner,CASE WHEN u.is_owner=1 OR EXISTS(SELECT 1 FROM user_roles ur WHERE ur.user_id=u.id AND ur.role_id='role-admin') THEN 1 ELSE 0 END is_admin FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.revoked_at IS NULL AND s.expires_at>? AND u.status='active'`).bind(await sha256(token),Math.floor(Date.now()/1000)).first<{id:string;username:string;display_name:string;is_owner:number;is_admin:number}>();return row?{id:row.id,username:row.username,displayName:row.display_name,isOwner:Boolean(row.is_owner),isAdmin:Boolean(row.is_admin)}:null}
function json(value:unknown,status=200){return new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin','X-Frame-Options':'DENY','Permissions-Policy':'camera=(), microphone=(), geolocation=()'}})}
function sameOrigin(request:Request){const origin=request.headers.get('Origin');return !origin||origin===new URL(request.url).origin}
async function readBody(request:Request):Promise<Record<string,unknown>>{if(!(request.headers.get('Content-Type')??'').includes('application/json'))throw new Error('JSON_REQUIRED');const value:unknown=await request.json();if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('INVALID_BODY');return value as Record<string,unknown>}
function text(value:unknown,max:number){return typeof value==='string'?value.trim().slice(0,max):''}
function nullable(value:unknown,max:number){const result=text(value,max);return result||null}
function now(){return Math.floor(Date.now()/1000)}
async function settings(env:FeedbackCentreEnv){const rows=await env.DB.prepare(`SELECT setting_key,setting_value FROM site_settings WHERE setting_key IN ('beta_enabled','beta_message','release_name','release_notes','known_issues','release_commit','release_previous_commit','release_deployed_at')`).all<{setting_key:string;setting_value:string}>();return Object.fromEntries(rows.results.map(row=>[row.setting_key,row.setting_value])) as Record<string,string>}
async function audit(env:FeedbackCentreEnv,actor:string,type:string,targetId:string|null,metadata:unknown={}){await env.DB.prepare(`INSERT INTO audit_events(id,actor_user_id,event_type,target_type,target_id,metadata_json,created_at) VALUES(?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),actor,type,'feedback_report',targetId,JSON.stringify(metadata),now()).run()}
function releasePayload(env:FeedbackCentreEnv,values:Record<string,string>){return{environment:env.APP_ENV,name:values.release_name||'Grev.dad Live Beta',currentCommit:values.release_commit||'Pending deployment marker',previousCommit:values.release_previous_commit||null,deployedAt:Number(values.release_deployed_at||0)||null,notes:values.release_notes||'',knownIssues:values.known_issues||''}}
async function config(env:FeedbackCentreEnv,user:Viewer){const values=await settings(env);return json({ok:true,betaEnabled:values.beta_enabled!=='0',betaMessage:values.beta_message||'Grev.dad is in live beta. Please report anything broken, confusing or unfinished.',canAdmin:user.isAdmin,release:releasePayload(env,values)})}
async function createReport(request:Request,env:FeedbackCentreEnv,user:Viewer){const data=await readBody(request),category=text(data.category,40),title=text(data.title,140),description=text(data.description,6000),expected=text(data.expected,3000),screenshot=nullable(data.screenshotDataUrl,1400000),pageUrl=text(data.pageUrl,1200),pageTitle=text(data.pageTitle,240);if(!CATEGORIES.has(category))return json({ok:false,message:'Choose a valid feedback category.'},400);if(!title||!description)return json({ok:false,message:'Add a title and describe what happened.'},400);if(screenshot&&!/^data:image\/(png|jpeg|webp);base64,/i.test(screenshot))return json({ok:false,message:'Screenshots must be PNG, JPEG or WebP images.'},400);const diagnostics=data.diagnostics&&typeof data.diagnostics==='object'&&!Array.isArray(data.diagnostics)?data.diagnostics:{};const diagnosticJson=JSON.stringify(diagnostics).slice(0,30000),values=await settings(env),id=crypto.randomUUID(),timestamp=now();await env.DB.prepare(`INSERT INTO feedback_reports(id,reporter_user_id,category,title,description,expected_result,screenshot_data,page_url,page_title,user_agent,viewport_json,diagnostics_json,environment,build_commit,status,severity,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,user.id,category,title,description,expected,screenshot,pageUrl,pageTitle,text(request.headers.get('User-Agent'),600),JSON.stringify((diagnostics as Record<string,unknown>).viewport??{}).slice(0,1000),diagnosticJson,env.APP_ENV,values.release_commit||null,'new','medium',timestamp,timestamp).run();await audit(env,user.id,'feedback.report_created',id,{category,pageUrl,environment:env.APP_ENV});return json({ok:true,id,message:'Thanks — your report has been sent to the site administrators.'},201)}
async function myReports(env:FeedbackCentreEnv,user:Viewer){const rows=await env.DB.prepare(`SELECT id,category,title,status,severity,created_at,updated_at FROM feedback_reports WHERE reporter_user_id=? ORDER BY created_at DESC LIMIT 50`).bind(user.id).all<Record<string,unknown>>();return json({ok:true,reports:rows.results.map(row=>({id:row.id,category:row.category,title:row.title,status:row.status,severity:row.severity,createdAt:row.created_at,updatedAt:row.updated_at}))})}
async function adminList(request:Request,env:FeedbackCentreEnv){const url=new URL(request.url),status=text(url.searchParams.get('status'),40),category=text(url.searchParams.get('category'),40);const rows=await env.DB.prepare(`SELECT r.*,u.username reporter_username,u.display_name reporter_name,a.username assigned_username,d.title duplicate_title FROM feedback_reports r JOIN users u ON u.id=r.reporter_user_id LEFT JOIN users a ON a.id=r.assigned_user_id LEFT JOIN feedback_reports d ON d.id=r.duplicate_of WHERE (?='' OR r.status=?) AND (?='' OR r.category=?) ORDER BY CASE r.severity WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,r.created_at DESC LIMIT 250`).bind(status,status,category,category).all<Record<string,unknown>>();const values=await settings(env);return json({ok:true,release:releasePayload(env,values),settings:{betaEnabled:values.beta_enabled!=='0',betaMessage:values.beta_message||'',releaseName:values.release_name||'',releaseNotes:values.release_notes||'',knownIssues:values.known_issues||''},reports:rows.results.map(row=>({id:row.id,category:row.category,title:row.title,description:row.description,expectedResult:row.expected_result,screenshotDataUrl:row.screenshot_data,pageUrl:row.page_url,pageTitle:row.page_title,userAgent:row.user_agent,viewport:row.viewport_json?JSON.parse(String(row.viewport_json)):null,diagnostics:row.diagnostics_json?JSON.parse(String(row.diagnostics_json)):null,environment:row.environment,buildCommit:row.build_commit,status:row.status,severity:row.severity,assignedUserId:row.assigned_user_id,assignedUsername:row.assigned_username,internalNotes:row.internal_notes,duplicateOf:row.duplicate_of,duplicateTitle:row.duplicate_title,reporter:{id:row.reporter_user_id,username:row.reporter_username,displayName:row.reporter_name},createdAt:row.created_at,updatedAt:row.updated_at,resolvedAt:row.resolved_at}))})}
async function updateReport(request:Request,env:FeedbackCentreEnv,user:Viewer,id:string){const current=await env.DB.prepare(`SELECT status,severity,assigned_user_id,internal_notes,duplicate_of FROM feedback_reports WHERE id=?`).bind(id).first<{status:string;severity:string;assigned_user_id:string|null;internal_notes:string|null;duplicate_of:string|null}>();if(!current)return json({ok:false,message:'Feedback report not found.'},404);const data=await readBody(request),status=text(data.status,40)||current.status,severity=text(data.severity,40)||current.severity,assignedUserId=data.assignedUserId===null?null:nullable(data.assignedUserId,80)??current.assigned_user_id,internalNotes=data.internalNotes===null?null:nullable(data.internalNotes,8000)??current.internal_notes,duplicateOf=data.duplicateOf===null?null:nullable(data.duplicateOf,80)??current.duplicate_of;if(!STATUSES.has(status)||!SEVERITIES.has(severity))return json({ok:false,message:'Choose a valid status and severity.'},400);const timestamp=now(),resolvedAt=['fixed','cannot_reproduce','closed'].includes(status)?timestamp:null;await env.DB.prepare(`UPDATE feedback_reports SET status=?,severity=?,assigned_user_id=?,internal_notes=?,duplicate_of=?,resolved_at=?,updated_at=? WHERE id=?`).bind(status,severity,assignedUserId,internalNotes,duplicateOf,resolvedAt,timestamp,id).run();await env.DB.prepare(`INSERT INTO feedback_report_events(id,report_id,actor_user_id,event_type,metadata_json,created_at) VALUES(?,?,?,?,?,?)`).bind(crypto.randomUUID(),id,user.id,'updated',JSON.stringify({status,severity,assignedUserId,duplicateOf}),timestamp).run();await audit(env,user.id,'feedback.report_updated',id,{status,severity});return json({ok:true})}
async function updateSettings(request:Request,env:FeedbackCentreEnv,user:Viewer){const data=await readBody(request),entries:[string,string][]=[['beta_enabled',data.betaEnabled===false?'0':'1'],['beta_message',text(data.betaMessage,240)],['release_name',text(data.releaseName,100)],['release_notes',text(data.releaseNotes,12000)],['known_issues',text(data.knownIssues,12000)]],timestamp=now();for(const[key,value]of entries)await env.DB.prepare(`INSERT INTO site_settings(setting_key,setting_value,updated_by,updated_at) VALUES(?,?,?,?) ON CONFLICT(setting_key) DO UPDATE SET setting_value=excluded.setting_value,updated_by=excluded.updated_by,updated_at=excluded.updated_at`).bind(key,value,user.id,timestamp).run();await audit(env,user.id,'feedback.settings_updated',null,{betaEnabled:data.betaEnabled!==false});return json({ok:true})}
export async function handleFeedbackCentreRequest(request:Request,env:FeedbackCentreEnv):Promise<Response|null>{const url=new URL(request.url),path=url.pathname;if(!path.startsWith('/api/feedback')&&!path.startsWith('/api/admin/feedback'))return null;const user=await viewerFromRequest(request,env);if(!user)return json({ok:false,message:'Authentication required.'},401);if(request.method!=='GET'&&!sameOrigin(request))return json({ok:false,message:'Origin rejected.'},403);if(path==='/api/feedback/config'&&request.method==='GET')return config(env,user);if(path==='/api/feedback/reports'&&request.method==='POST')return createReport(request,env,user);if(path==='/api/feedback/reports/mine'&&request.method==='GET')return myReports(env,user);if(!user.isAdmin)return json({ok:false,message:'Administrator access required.'},403);if(path==='/api/admin/feedback'&&request.method==='GET')return adminList(request,env);if(path==='/api/admin/feedback/settings'&&request.method==='PUT')return updateSettings(request,env,user);const match=path.match(/^\/api\/admin\/feedback\/([0-9a-f-]{36})$/i);if(match&&request.method==='PATCH')return updateReport(request,env,user,match[1]!);return json({ok:false,message:'Feedback route not found.'},404)}