interface D1Result<T> { results: T[]; }
interface D1Statement {
  bind(...values: unknown[]): D1Statement;
  first<T = Record<string, unknown>>(): Promise<T | null>;
  all<T = Record<string, unknown>>(): Promise<D1Result<T>>;
  run(): Promise<unknown>;
}
interface D1Database { prepare(query: string): D1Statement; batch(statements: D1Statement[]): Promise<unknown[]>; }

export interface GrevNewsSubscriptionsEnv { DB: D1Database; }

type SubscriptionType = 'grev'|'cs2'|'team';
type Subscription = { type: SubscriptionType; key: string; label: string };
type Viewer = { id: string };
type NewsRow = Record<string, unknown> & { category?: string; team_tags_json?: string };

const COOKIE='grev_session';
const encoder=new TextEncoder();
const GREV_CATEGORIES=new Set(['grev','site','community']);
const CS2_CATEGORIES=new Set(['cs2','team']);

function b64(bytes:Uint8Array):string{return btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');}
async function sha256(value:string):Promise<string>{return b64(new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(value))));}
function cookies(request:Request):Record<string,string>{return Object.fromEntries((request.headers.get('Cookie')??'').split(';').map(value=>value.trim()).filter(Boolean).map(value=>{const index=value.indexOf('=');return index<0?['','']:[value.slice(0,index),decodeURIComponent(value.slice(index+1))];}).filter(([key])=>Boolean(key)));}
function json(value:unknown,status=200):Response{return new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin','X-Frame-Options':'DENY','Permissions-Policy':'camera=(), microphone=(), geolocation=()'}});}
function sameOrigin(request:Request):boolean{const origin=request.headers.get('Origin');return !origin||origin===new URL(request.url).origin;}
function now():number{return Math.floor(Date.now()/1000);}
async function viewer(request:Request,env:GrevNewsSubscriptionsEnv):Promise<Viewer|null>{const token=cookies(request)[COOKIE];if(!token)return null;const row=await env.DB.prepare(`SELECT u.id FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.revoked_at IS NULL AND s.expires_at>? AND u.status='active'`).bind(await sha256(token),now()).first<{id:string}>();return row?{id:row.id}:null;}
async function readBody(request:Request):Promise<Record<string,unknown>>{if(!(request.headers.get('Content-Type')??'').includes('application/json'))throw new Error('A JSON request body is required.');const value:unknown=await request.json();if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('A valid request body is required.');return value as Record<string,unknown>;}
function parseJsonList(value:unknown):string[]{try{const parsed=typeof value==='string'?JSON.parse(value):value;return Array.isArray(parsed)?parsed.filter((item):item is string=>typeof item==='string').map(item=>item.trim()).filter(Boolean):[];}catch{return[];}}
function teamLabel(value:unknown):string{return String(value??'').replace(/\s+/g,' ').trim().slice(0,80);}
function teamKey(value:unknown):string{return teamLabel(value).toLocaleLowerCase('en-GB');}

async function ensureInitialized(env:GrevNewsSubscriptionsEnv,userId:string):Promise<void>{const existing=await env.DB.prepare(`SELECT user_id FROM grev_news_dashboard_preferences WHERE user_id=?`).bind(userId).first();if(existing)return;const timestamp=now();await env.DB.batch([env.DB.prepare(`INSERT OR IGNORE INTO grev_news_subscriptions(user_id,subscription_type,subscription_key,label,created_at) VALUES(?,?,?,?,?)`).bind(userId,'grev','grev','Grev News',timestamp),env.DB.prepare(`INSERT OR IGNORE INTO grev_news_dashboard_preferences(user_id,selected_scope,initialized_at,updated_at) VALUES(?,?,?,?)`).bind(userId,'subscribed',timestamp,timestamp)]);}
async function subscriptions(env:GrevNewsSubscriptionsEnv,userId:string):Promise<Subscription[]>{await ensureInitialized(env,userId);return (await env.DB.prepare(`SELECT subscription_type,subscription_key,label FROM grev_news_subscriptions WHERE user_id=? ORDER BY CASE subscription_type WHEN 'grev' THEN 0 WHEN 'cs2' THEN 1 ELSE 2 END,label`).bind(userId).all<{subscription_type:SubscriptionType;subscription_key:string;label:string}>()).results.map(row=>({type:row.subscription_type,key:row.subscription_key,label:row.label}));}
function allowedScope(scope:string,items:Subscription[]):boolean{if(scope==='subscribed')return true;if(scope==='grev')return items.some(item=>item.type==='grev');if(scope==='cs2')return items.some(item=>item.type==='cs2');if(scope.startsWith('team:'))return items.some(item=>item.type==='team'&&item.key===scope.slice(5));return false;}
async function availableTeams(env:GrevNewsSubscriptionsEnv,items:Subscription[]):Promise<string[]>{const labels=new Map<string,string>();for(const item of items)if(item.type==='team')labels.set(item.key,item.label);const rows=(await env.DB.prepare(`SELECT team_tags_json FROM grev_news_posts WHERE status='published' ORDER BY published_at DESC LIMIT 500`).all<{team_tags_json:string}>()).results;for(const row of rows)for(const label of parseJsonList(row.team_tags_json)){const clean=teamLabel(label),key=teamKey(clean);if(clean&&key&&!labels.has(key))labels.set(key,clean);}return [...labels.values()].sort((a,b)=>a.localeCompare(b,'en-GB',{sensitivity:'base'}));}
async function preference(env:GrevNewsSubscriptionsEnv,userId:string):Promise<string>{await ensureInitialized(env,userId);const row=await env.DB.prepare(`SELECT selected_scope FROM grev_news_dashboard_preferences WHERE user_id=?`).bind(userId).first<{selected_scope:string}>();return row?.selected_scope??'subscribed';}
function subscriptionPayload(items:Subscription[]){return{grev:items.some(item=>item.type==='grev'),cs2:items.some(item=>item.type==='cs2'),teams:items.filter(item=>item.type==='team').map(item=>({key:item.key,label:item.label}))};}
async function snapshot(env:GrevNewsSubscriptionsEnv,userId:string):Promise<Response>{const items=await subscriptions(env,userId);let dashboardFilter=await preference(env,userId);if(!allowedScope(dashboardFilter,items)){dashboardFilter='subscribed';await env.DB.prepare(`UPDATE grev_news_dashboard_preferences SET selected_scope=?,updated_at=? WHERE user_id=?`).bind(dashboardFilter,now(),userId).run();}return json({subscriptions:subscriptionPayload(items),availableTeams:await availableTeams(env,items),dashboardFilter});}

function postMatches(row:NewsRow,scope:string,items:Subscription[]):boolean{const category=String(row.category??'');const tags=parseJsonList(row.team_tags_json).map(teamKey);const grev=items.some(item=>item.type==='grev');const cs2=items.some(item=>item.type==='cs2');const teams=items.filter(item=>item.type==='team').map(item=>item.key);if(scope==='grev')return GREV_CATEGORIES.has(category);if(scope==='cs2')return CS2_CATEGORIES.has(category);if(scope.startsWith('team:'))return tags.includes(scope.slice(5));return(grev&&GREV_CATEGORIES.has(category))||(cs2&&CS2_CATEGORIES.has(category))||teams.some(key=>tags.includes(key));}
async function personalized(request:Request,env:GrevNewsSubscriptionsEnv,userId:string):Promise<Response>{const url=new URL(request.url);const items=await subscriptions(env,userId);const requested=(url.searchParams.get('scope')??'subscribed').trim();const scope=allowedScope(requested,items)?requested:'subscribed';const limit=Math.max(1,Math.min(100,Number(url.searchParams.get('limit')??40)));const query=(url.searchParams.get('q')??'').trim().toLocaleLowerCase('en-GB');const rows=(await env.DB.prepare(`SELECT id,title,summary,body,category,team_tags_json,status,is_featured,source_name,source_url,image_url,published_at,created_at,updated_at FROM grev_news_posts WHERE status='published' ORDER BY is_featured DESC,published_at DESC LIMIT 250`).all<NewsRow>()).results.filter(row=>postMatches(row,scope,items)).filter(row=>!query||`${String(row.title??'')} ${String(row.summary??'')} ${parseJsonList(row.team_tags_json).join(' ')}`.toLocaleLowerCase('en-GB').includes(query)).slice(0,limit).map(row=>({...row,teamTags:parseJsonList(row.team_tags_json),team_tags_json:undefined}));return json({posts:rows,scope,subscriptions:subscriptionPayload(items),generatedAt:now()});}

async function saveSubscriptions(request:Request,env:GrevNewsSubscriptionsEnv,userId:string):Promise<Response>{const input=await readBody(request);const timestamp=now();const grev=input.grev!==false;const cs2=input.cs2===true;const rawTeams=Array.isArray(input.teams)?input.teams:[];const teams=[...new Map(rawTeams.map(team=>{const label=teamLabel(team),key=teamKey(label);return[key,label] as const;}).filter(([key,label])=>Boolean(key&&label))).entries()].slice(0,40);const statements:D1Statement[]=[env.DB.prepare(`DELETE FROM grev_news_subscriptions WHERE user_id=?`).bind(userId)];if(grev)statements.push(env.DB.prepare(`INSERT INTO grev_news_subscriptions(user_id,subscription_type,subscription_key,label,created_at) VALUES(?,?,?,?,?)`).bind(userId,'grev','grev','Grev News',timestamp));if(cs2)statements.push(env.DB.prepare(`INSERT INTO grev_news_subscriptions(user_id,subscription_type,subscription_key,label,created_at) VALUES(?,?,?,?,?)`).bind(userId,'cs2','cs2','CS2 updates',timestamp));for(const[key,label]of teams)statements.push(env.DB.prepare(`INSERT INTO grev_news_subscriptions(user_id,subscription_type,subscription_key,label,created_at) VALUES(?,?,?,?,?)`).bind(userId,'team',key,label,timestamp));statements.push(env.DB.prepare(`INSERT OR IGNORE INTO grev_news_dashboard_preferences(user_id,selected_scope,initialized_at,updated_at) VALUES(?,?,?,?)`).bind(userId,'subscribed',timestamp,timestamp));await env.DB.batch(statements);const items=await subscriptions(env,userId);const current=await preference(env,userId);if(!allowedScope(current,items))await env.DB.prepare(`UPDATE grev_news_dashboard_preferences SET selected_scope='subscribed',updated_at=? WHERE user_id=?`).bind(timestamp,userId).run();return snapshot(env,userId);}
async function saveDashboardPreference(request:Request,env:GrevNewsSubscriptionsEnv,userId:string):Promise<Response>{const input=await readBody(request);const scope=String(input.scope??'subscribed').trim();const items=await subscriptions(env,userId);if(!allowedScope(scope,items))return json({ok:false,message:'Choose one of your subscribed news feeds.'},400);const timestamp=now();await env.DB.prepare(`INSERT INTO grev_news_dashboard_preferences(user_id,selected_scope,initialized_at,updated_at) VALUES(?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET selected_scope=excluded.selected_scope,updated_at=excluded.updated_at`).bind(userId,scope,timestamp,timestamp).run();return json({ok:true,dashboardFilter:scope});}

export async function handleGrevNewsSubscriptionsRequest(request:Request,env:GrevNewsSubscriptionsEnv):Promise<Response|null>{const path=new URL(request.url).pathname;if(!['/api/news/subscriptions','/api/news/dashboard-preference','/api/news/personalized'].includes(path))return null;const current=await viewer(request,env);if(!current)return json({ok:false,message:'Authentication required.'},401);if(request.method!=='GET'&&!sameOrigin(request))return json({ok:false,message:'Origin rejected.'},403);try{if(path==='/api/news/subscriptions'&&request.method==='GET')return snapshot(env,current.id);if(path==='/api/news/subscriptions'&&request.method==='PUT')return saveSubscriptions(request,env,current.id);if(path==='/api/news/dashboard-preference'&&request.method==='PUT')return saveDashboardPreference(request,env,current.id);if(path==='/api/news/personalized'&&request.method==='GET')return personalized(request,env,current.id);}catch(error){return json({ok:false,message:error instanceof Error?error.message:'The news subscription request failed.'},400);}return json({ok:false,message:'Method not allowed.'},405);}
